#!/bin/bash

if [ $1 ] ; then
	case $1 in
		compile)   {
			export GRAMMAR_PATH="/Users/ulissesaraujocosta/ulisses/univ/msc/el/eg/trabalhos/"
			SILVER_DIR="$GRAMMAR_PATH/Silver/trunk/jars"

			time java -jar $SILVER_DIR/RunSilver.jar  Lisp1  \
				&& ant 
		}  ;;
		run)    java -jar Lisp1.jar $2 ;;
		*)      echo "'$1' cannot be extracted via extract()" ;;
	esac
else
	echo "'$1' is not a valid file"
fi

