#!/usr/bin/perl

use strict;

my @left;
my @rigth;

my %leftP;
my %rightP;

my $input = "";
my $symbol;

while(<>){

	$input .= $_;
	if(m/^([A-Z\'\+]+)\s+:\s*$/){
		$leftP{$1}++;
	}
	if(m/^([A-Z\'\+]+)\s+:\s+([A-Z\'\+]+)/){
		$leftP{$1}++;
		$rightP{$2}++;
	}

	if(m/^([A-Z\'\+]+)\s+:\s+([A-Z\'\+]+)\s+([A-Z\'\+]+)/){
		$leftP{$1}++;
		$rightP{$2}++;
		$rightP{$3}++;
	}

	if(m/^\s+\|\s+([A-Z\'\+]+)/){
		$rightP{$1}++;
	}

	if(m/^\s+\|\s+([A-Z\'\+]+)\s+([A-Z\'\+]+)/){
		$rightP{$1}++;
		$rightP{$2}++;
	}
}

for $symbol (keys (%leftP)) {
	$input =~ s/([^A-Za-z\+\']$symbol[^A-Za-z\+\'])/\L$1/g;
	$input =~ s/([^A-Za-z\+\']$symbol[^A-Za-z\+\'])/\L$1/g;
}

print "Gramática Portuguesa:\n";
for $symbol (keys (%leftP)) {
	if($rightP{$symbol}){
		
	}else{
		print " - símbolo inicial: \L$symbol \n\n";
	}
}

print $input;

print "\n\nSímbolos Não-Terminais:\n";
for $symbol (keys (%leftP)) {
	print "\L$symbol ";
}

print "\n\nSímbolos Terminais:\n";
for $symbol (keys (%rightP)){
	if($leftP{$symbol}){
		
	}else{
		print "$symbol ";
	}
}
print "\n";

__END__

ADJ		Adjectivo							#bom, brilhante, eficaz, …
ADV		Advérbio							#hoje, já, sim, felizmente, …
CARD		Cardinal							#zero, dez, cem, mil, …
CJ		Conjunção							#e, ou, tal como, …
CL		Cliticos							#o, lhe, se, …
CN		Nome								#computador, cidade, ideia, …
DA		Artigo Definido							#o, os, …
DEM		Demonstrativo							#este, esses, aquele, …
DFR		Fracções							#meio, terço, décimo, %, …
DGTR		Números Romanos							#VI, LX, MMIII, MCMXCIX, …
DGT		Dígitos								#0, 1, 42, 12345, 67890, …
DM		Marcadores de Discurso						#olá, …
EADR		Endereço Electrónico						#http://www.di.fc.ul.pt, …
EOE		Final de Enumeração						#etc
EXC		Exclamativa							#ah, ei, etc.
GER		Gerúndio							#sendo, afirmando, vivendo, …
GERAUX		Gerúndio 							#"ter"/"haver" em termos compostos	tendo, havendo …
IA		Artigo Indefinido						#uns, umas, …
IND		Indefinidos							#tudo, alguém, ninguém, …
INF		Infinitivo							#ser, afirmar, viver, …
INFAUX		Infinitivo 							#"ter"/"haver" em termos compostos	ter, haver …
INT		Interrogativos							#quem, como, quando, …
ITJ		Interjeição							#bolas, caramba, …
LTR		Letras								#a, b, c, …
MGT		Classe de Magnitude						#unidade, dezena, dúzia, resma, …
MTH		Meses								#Janeiro, Dezembro, …
NP		Sintagma Nominal						#idem, …
ORD		Ordinal								#primeiro, centésimo, penúltimo, …
PADR		Parte de Endereço						#Rua, av., rot., …
PNM		Parte de Nome Próprio						#Lisboa, António, João, …
PNT		Pontuação							#., ?, (, …
POSS		Possessivos							#meu, teu, seu, …
PPA		Particípio Passado que não ocorre em termos compostos		#afirmados, vivida, …
PP		Sintagma Preposicional						#algures, …
PPT		Particípio Passado em termos compostos				#sido, afirmado, vivido, …
PREP		Preposição							#de, para, em redor de, …
PRS		Pronome Pessoal							#eu, tu, ele, …
QNT		Quantificadores							#todos, muitos, nenhum, …
REL		Pronome Relativo						#que, cujo, tal que, …
STT		Títulos Sociais							#Presidente, drª., prof., …
SYB		Símbolos							#@, #, &, …
TERMN		Terminações opcionais						#(s), (as), …
UM		"um" ou "uma"							#um, uma
UNIT		Abreviatura de unidade de medida				#kg., km., …
VAUX		Verbos finitos "ter" ou "haver" em forma verbal compost		#temos, haveriam, …
V		Verbos								#falou, falaria, …
WD		Dias da Semana							#segunda, terça-feira, sábado, …
